version: '3.2'
services:
  proxy.cadc.dao.nrc.ca:
    hostname: proxy.cadc.dao.nrc.ca
    image: nginx:alpine
    ports:
      - '80:80'
    networks:
      - 'selenium'
    volumes:
      - './default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - search.cadc.dao.nrc.ca
      - caom2-meta-ui.cadc.dao.nrc.ca
  selenium-firefox:
    image: selenium/standalone-firefox:3
    ports:
      - '4444:4444'
    networks:
      - 'selenium'
    depends_on:
      - proxy.cadc.dao.nrc.ca
  search.cadc.dao.nrc.ca:
    image: opencadc/caom2-search:SNAPSHOT
    networks:
      - 'selenium'
    depends_on:
      - uwspg.cadc.dao.nrc.ca
      - caom2-meta-ui.cadc.dao.nrc.ca
    environment:
      CATALINA_OPTS: -Dca.nrc.cadc.reg.client.RegistryClient.host=proxy.cadc.dao.nrc.ca
  uwspg.cadc.dao.nrc.ca:
    image: opencadc/uws-postgres:alpine
    networks:
      - 'selenium'
    environment:
      POSTGRES_USER: uws
      POSTGRES_PASSWORD: astr0query
  caom2-meta-ui.cadc.dao.nrc.ca:
    image: opencadc/caom2-meta-ui:SNAPSHOT
    networks:
      - 'selenium'
    environment:
      CATALINA_OPTS: -Dca.nrc.cadc.reg.client.RegistryClient.host=proxy.cadc.dao.nrc.ca


# Create the network 'selenium' for which this system will run within.
networks:
  selenium:
