version: '3.2'
services:
  proxy.cadc.dao.nrc.ca:
    hostname: proxy.cadc.dao.nrc.ca
    image: nginx:alpine
    ports:
      - '80:80'
    networks:
      - 'selenium'
    volumes:
      - './default.conf:/etc/nginx/conf.d/default.conf'
      - './_ROOT_:/usr/share/nginx/html'
    depends_on:
      - search.cadc.dao.nrc.ca
      - caom2-meta-ui.cadc.dao.nrc.ca   
  selenium-firefox:
    image: selenium/standalone-firefox:3.10.0
    ports:
      - '4444:4444'
    networks:
      - 'selenium'
  search.cadc.dao.nrc.ca:
    image: opencadc/archive-search:SNAPSHOT
    ports:
      - '8080:8080'
      - '5555:5555'
    networks:
      - 'selenium'
    depends_on:
      - uwspg.cadc.dao.nrc.ca
    environment:
      - CATALINA_OPTS=-Dca.nrc.cadc.reg.client.RegistryClient.host=proxy.cadc.dao.nrc.ca 
  uwspg.cadc.dao.nrc.ca:
    image: opencadc/uws-postgres:alpine
    networks:
      - 'selenium'
    environment:
      - POSTGRES_USER=uws
      - POSTGRES_PASSWORD=astr0query
  caom2-meta-ui.cadc.dao.nrc.ca:
    image: opencadc/caom2-meta-ui:alpine
    ports:
      - '5556:5555'
    networks:
      - 'selenium'
    environment:
      - CATALINA_OPTS=-Dca.nrc.cadc.reg.client.RegistryClient.host=proxy.cadc.dao.nrc.ca 


# Create the network 'selenium' for which this system will run within.
networks:
  selenium:
